# Generated by Django 3.1 on 2020-10-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistlisting',
            name='listing_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='wishlistlisting',
            name='moneyOffer',
            field=models.DecimalField(decimal_places=2, help_text="Amount that you are offering for the items you're seeking.", max_digits=9, primary_key=True, serialize=False, verbose_name='Money Offer'),
        ),
    ]
