# Generated by Django 3.1 on 2020-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='banUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='handleEvents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='handleImages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='handleListings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='handleRatings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='handleWishlists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='superAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='warnUser',
            field=models.BooleanField(default=False),
        ),
    ]
