# Generated by Django 3.1 on 2020-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='minimumIncrement',
            field=models.DecimalField(decimal_places=2, help_text='Minimum increment bid that can be placed on the auction, that cannot be greater than the starting bid (maximum increment bid will be x3 this value).', max_digits=9, verbose_name='Minimum Increment'),
        ),
    ]
