# Generated by Django 3.1 on 2020-11-22 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_report_reporttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingValue',
            field=models.IntegerField(default=1, help_text='Rating for user from 1 to 5, 5 being the best.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
