# Generated by Django 3.1 on 2020-10-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201003_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistlisting',
            name='moneyOffer',
        ),
        migrations.AlterField(
            model_name='wishlistlisting',
            name='listing_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing'),
        ),
    ]
