# Generated by Django 3.1 on 2020-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200820_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='superAdmin',
            field=models.BooleanField(default=False, help_text='Admin that is able to set, remove and configure other Admin accounts.', verbose_name='Super Admin'),
        ),
    ]
