# Generated by Django 3.1 on 2020-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200825_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlisting',
            name='maxRange',
            field=models.DecimalField(decimal_places=2, default=None, help_text="Maximum money offers you'll consider (leave blank if you don't have a maximum).", max_digits=9, verbose_name='Maximum Price Range'),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='minRange',
            field=models.DecimalField(decimal_places=2, default=None, help_text="Minimum money offers you'll consider.", max_digits=9, verbose_name='Minimum Price Range'),
        ),
    ]
