# Generated by Django 3.1 on 2020-08-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200824_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='autobuy',
            field=models.DecimalField(decimal_places=2, default=None, help_text='If a user bids the amount you set in this field, the auction will close and they will win the auction.', max_digits=9),
        ),
    ]
