# Generated by Django 3.1 on 2020-08-22 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketapp\\listings\\images')),
                ('name', models.TextField(max_length=50, verbose_name='Name of Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(help_text='Qualities of the item in the photo, purpose and where one can find it can be used as tags.', to='listings.Tag', verbose_name='Item Tags')),
            ],
        ),
    ]
