# Generated by Django 3.1 on 2020-08-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200820_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='banUser',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='warnUser',
        ),
    ]
