# Generated by Django 3.1 on 2020-10-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201003_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistlisting',
            name='moneyOffer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Amount that you are offering for the items you're seeking.", max_digits=9, verbose_name='Money Offer'),
            preserve_default=False,
        ),
    ]
