# Generated by Django 3.1 on 2020-10-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_wishlistlisting_moneyoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistlisting',
            name='moneyOffer',
            field=models.DecimalField(decimal_places=2, help_text="Amount that you are offering for the items you're seeking.", max_digits=9, null=True, verbose_name='Money Offer'),
        ),
    ]
