# Generated by Django 3.1 on 2020-12-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20201122_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='actionTaken',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
