# Generated by Django 3.1 on 2020-08-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Item Name')),
                ('description', models.TextField(help_text='A brief description of the item in the image(s).', max_length=250)),
                ('image', models.ManyToManyField(to='listings.Image')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.wishlist')),
            ],
        ),
    ]
