# Generated by Django 3.1 on 2020-08-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='image',
            new_name='images',
        ),
    ]
