# Generated by Django 3.1 on 2020-08-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200822_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Title of Event')),
                ('context', models.TextField(help_text='What is the event for?  What will happen/be accomplished?', max_length=250)),
                ('date', models.DateTimeField(verbose_name='Date and Time of Event')),
                ('location', models.TextField(max_length=100, verbose_name='Address where Event is Held')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
