# Generated by Django 3.1 on 2020-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200902_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlisting',
            name='maxRange',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Maximum money offers you'll consider (leave blank if you don't have a maximum).", max_digits=9, verbose_name='Maximum Price Range'),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='minRange',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Minimum money offers you'll consider.", max_digits=9, verbose_name='Minimum Price Range'),
        ),
    ]
