# Generated by Django 3.1 on 2020-08-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('openToMoneyOffers', models.BooleanField(default=True, help_text="Leave this field unchecked if you're only interested in item offers.", verbose_name='Open to Money Offers?')),
                ('minRange', models.DecimalField(decimal_places=2, help_text="Minimum money offers you'll consider.", max_digits=9, verbose_name='Minimum Price Range')),
                ('maxRange', models.DecimalField(decimal_places=2, help_text="Maximum money offers you'll consider (leave blank if you don't have a maximum).", max_digits=9, verbose_name='Maximum Price Range')),
                ('notes', models.TextField(help_text="Include here what offers you're seeking.", max_length=500)),
            ],
            bases=('listings.listing',),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='A short description of what the listing obtains.', max_length=500, verbose_name='Listing Description'),
        ),
    ]
