# Generated by Django 3.1 on 2020-09-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200903_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='autobuy',
            field=models.DecimalField(decimal_places=2, default=None, help_text='If a user bids the amount you set in this field, the auction will close and they will win the auction.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='maxRange',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Maximum money offers you'll consider (leave blank if you don't have a maximum).", max_digits=9, null=True, verbose_name='Maximum Price Range'),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='minRange',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Minimum money offers you'll consider.", max_digits=9, null=True, verbose_name='Minimum Price Range'),
        ),
    ]
