# Generated by Django 3.1 on 2020-10-18 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20201015_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingName', models.TextField(max_length=100)),
                ('exchangeeAmountOffer', models.DecimalField(decimal_places=2, max_digits=9)),
                ('exchangee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_exchangee', to=settings.AUTH_USER_MODEL)),
                ('exchangeeItems', models.ManyToManyField(related_name='exchangee_items', to='listings.Item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_owner', to=settings.AUTH_USER_MODEL)),
                ('ownerItems', models.ManyToManyField(related_name='owner_items', to='listings.Item')),
            ],
        ),
    ]
