# Generated by Django 3.1 on 2020-10-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='exchangeeAmountOffer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='exchangeeItems',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='listingName',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='ownerItems',
        ),
        migrations.AddField(
            model_name='receipt',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='listings.listing'),
        ),
    ]
