# Generated by Django 3.1 on 2020-08-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200824_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('startingBid', models.DecimalField(decimal_places=2, help_text='Money amount bidding should start at for auction.', max_digits=9, verbose_name='Starting Bid')),
                ('minimumIncrement', models.DecimalField(decimal_places=2, help_text='Minimum increment bid that can be placed on the auction (maximum increment bid will be x3 this value).', max_digits=9, verbose_name='Minimum Increment')),
                ('endTimeChoices', models.CharField(choices=[('1h', 'One Hours'), ('2h', 'Two Hours'), ('4h', 'Four Hours'), ('8h', 'Eight Hours'), ('12h', 'Twelve Hours'), ('1d', 'One Day'), ('3d', 'Three Days'), ('7d', 'Seven Days')], default='1h', max_length=3)),
                ('endTime', models.DateTimeField(blank=True)),
                ('autobuy', models.DecimalField(decimal_places=2, default=None, help_text='If a user bids the amount you set in this field, the auction will close and they will win the auction.', max_digits=9, verbose_name='Starting Bid')),
                ('auctionEnded', models.BooleanField(default=False)),
            ],
            bases=('listings.listing',),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='maxRange',
            field=models.DecimalField(decimal_places=2, default=None, help_text="Maximum money offers you'll consider (leave blank if you don't have a maximum).", max_digits=9, verbose_name='Maximum Price Range'),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='minRange',
            field=models.DecimalField(decimal_places=2, default=None, help_text="Minimum money offers you'll consider.", max_digits=9, verbose_name='Minimum Price Range'),
        ),
    ]
