# Generated by Django 3.1 on 2020-09-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200905_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount of cash you'd like to offer on listing (leave blank if you do not want to offer cash).", max_digits=9, verbose_name='Cash Offer')),
                ('items', models.ManyToManyField(help_text="Items you'd like to offer on listing (do not select anything if you do not wanna offer items).", to='listings.Item')),
                ('offerListing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerlisting', to='listings.offerlisting')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
