# Generated by Django 3.1 on 2020-10-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20201022_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='listings.listing'),
        ),
    ]
