# Generated by Django 3.1 on 2020-09-10 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount of cash you'd like to bid on listing (Cannot be more than 3x the minimum bid value).", max_digits=9, verbose_name='Bid Amount')),
                ('winningBid', models.BooleanField(default=False)),
                ('auctionListing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionlisting', to='listings.auctionlisting')),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
