# Generated by Django 3.1 on 2020-08-24 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200824_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='auctionEnded',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='endTimeChoices',
        ),
        migrations.AddField(
            model_name='listing',
            name='endTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='endTimeChoices',
            field=models.CharField(choices=[('1h', 'One Hours'), ('2h', 'Two Hours'), ('4h', 'Four Hours'), ('8h', 'Eight Hours'), ('12h', 'Twelve Hours'), ('1d', 'One Day'), ('3d', 'Three Days'), ('7d', 'Seven Days')], default='1h', max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingEnded',
            field=models.BooleanField(default=False),
        ),
    ]
