# Generated by Django 3.1 on 2020-10-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20201022_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='listing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='listings.listing'),
        ),
    ]
