# Generated by Django 3.1 on 2020-09-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_listing_listingended'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerAccepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='offerlisting',
            name='listingCompleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
