# Generated by Django 3.1 on 2020-10-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20201023_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=9)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paymentDate', models.TextField(max_length=250)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipt', to='listings.receipt')),
            ],
        ),
    ]
