# Generated by Django 3.1 on 2020-09-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20200916_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images', width_field='width'),
        ),
    ]
