# Generated by Django 3.1 on 2020-10-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_paymentreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='netAmount',
        ),
    ]
