# Generated by Django 3.1 on 2020-10-30 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20201025_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('creationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_notification', to='listings.profile')),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('listings.notification',),
        ),
    ]
