# Generated by Django 3.1 on 2020-09-19 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200917_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerListing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerlisting', to='listings.offerlisting'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
