# Generated by Django 3.1 on 2020-10-30 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20201030_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.warning')),
            ],
            bases=('listings.notification',),
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.receipt')),
            ],
            bases=('listings.notification',),
        ),
        migrations.CreateModel(
            name='OfferNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.offer')),
            ],
            bases=('listings.notification',),
        ),
        migrations.CreateModel(
            name='ListingNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
            ],
            bases=('listings.notification',),
        ),
        migrations.CreateModel(
            name='InvitationNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.invitation')),
            ],
            bases=('listings.notification',),
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.event')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('listings.notification',),
        ),
        migrations.CreateModel(
            name='BidNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.notification')),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.bid')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
            ],
            bases=('listings.notification',),
        ),
    ]
