# Generated by Django 3.1 on 2020-11-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_bidnotification_eventnotification_invitationnotification_listingnotification_offernotification_payme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingnotification',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
