# Generated by Django 3.1 on 2020-09-29 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20200919_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auctionListing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='listings.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
