# Generated by Django 3.1 on 2020-11-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20201101_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
