# Generated by Django 3.1 on 2020-11-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_notification_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationnotification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.event'),
        ),
    ]
