# Generated by Django 3.1 on 2020-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
